### ISSUE TITLE
planiverse is 404

### ISSUE THREAD

**Issue by lvm** [tleb/awesome-mastodon#58]
https://github.com/FuzzJunket/planiverse

**Comment by SuperSandro2000** [comment]
How about https://github.com/Oreolek/planiverse ? or is this an old fork?

**Comment by lvm** [comment]
Hi @SuperSandro2000, 
I wouldn't know honestly. I was browsing the list for new stuff when found that dead link. 

That being said, this looks more up to date: https://git.mulligrubs.me/planiverse/ 
On `2020-06-21 15:07` was the last commit

**Comment by tleb** [comment]
I just went through everything to fix outdated links and I used @lvm's link for Planiverse; thank you!
